# ./server/Cargo.toml
[package]
name = "particle-life-server"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "particle-life-server"
path = "src/main.rs"

[dependencies]
actix-web = "4.4"
actix-files = "0.6"
env_logger = "0.11"
log = { workspace = true }

[build-dependencies]